import { createI18n } from 'vue-i18n';

const messages = {
  en: {
    message: {
      subtitle: 'Train and develop soft skills',
      paragraph1: 'Are you interested in Soft Skills and would like to integrate them into your practice?',
      paragraph2: 'Soft Skills are relational and human skills close to personality traits that are essential in professional life and that complement specialized skills and knowledge (Hard Skills). Each and every one of us acquires them partially regardless of our professional or personal background.',
      paragraph3: 'Today, however, Soft Skills training seems to be more naturally geared towards high-qualified people.',
      paragraph4: 'The Erasmus+ project " Soft skills " is aiming at facilitating access to soft skills for people with low levels of qualification and/or with disabilities, in order to favor their vocational and even social inclusion and equal opportunities. Mastering a professional activity does not only require the implementation of technical skills specific to the job (hard skills), it also relies on soft skills.',
      paragraph5: 'Our approach : to take into account the whole process of acquisition of Soft Skills. We developed  numerous complementary materials which are accessible on this website for free. ',
      paragraph6: 'In addition to these free materials, a digital platform called Zerobarrier, is accessible for a fee. This platform will allow you to manage and track  the process of Soft Skills acquisition.',
      button1: 'Impact measurement report-EN.pdf',
      subtitle2: 'Who are we ?',
      partners: 'It is within the framework of the European project "Soft Skills" co-financed by the Erasmus + program, that 9 European partners from France, Belgium, Spain, Austria and Slovenia have co-developed the materials that you will find on this website. These partners are active in the field of vocational training. Whether they are training centres, integration companies or adapted companies, they have an expertise in the training of people with a low level of qualification and/or a disability. Click on the logos to learn more about them.',
      pedagogy1title: 'EUROPEAN CATALOGUE OF SOFT SKILLS REFERENCES',
      pedagogy1text: 'The “European catalogue of soft skills references” gives an overview of the soft skills approach the project followed: it contains the list of soft skills defined within the framework of the project, the levels of acquisition and their definitions as well as a description of the soft skills acquisition process and the placement and assessment linked to it;',
      pedagogy1download1: 'Catalogue EN.pdf',
      pedagogy2title: 'SOFT SKILLS LIST WITH PICTOGRAMS',
      pedagogy2text: 'This document illustrates the 5 categories and the 20 soft skills defined in the project using pictograms. A good communication document and a good pedagogical support to remember and retain the soft skills and their definitions.',
      pedagogy2download1: 'Soft skills list with pictograms EN finalized 16 07 21.pdf',
      pedagogy3title: 'SOFT SKILLS BASE',
      pedagogy3text: 'The Soft Skills base is a document that brings together in a table all the definitions of the categories and Soft Skills by level as well as the observable behaviours and life situations that are related to them.',
      pedagogy3download1: 'Soft skills base 27 07 2021 - finalized EN.xlsx',
      pedagogy4title: 'WHEELS',
      pedagogy4text: 'This document illustrates the 5 categories and the 20 soft skills defined in the project using wheels. These wheels are a good way to visualize your level of soft skills and can be used during a placement or an Assessment.',
      pedagogy4download1: 'Wheels EN finalized 16 07 2021.pdf',
      pedagogy5title: 'SUMMARY OF THE SOFT SKILLS ACQUISITION PROCESS',
      pedagogy5text: 'This sheet gives an overview of the 3 steps of the Soft Skills acquisition process as well as the tools that can be used at each step. It will help the trainer to keep in mind all the elements that will be useful and to look at the process in its entirety',
      pedagogy5download1: 'Summary of the project EN.pdf',
      pedagogy6title: 'ZEROBARRIER MANUAL',
      pedagogy6text: 'Manual that explains how to use the Zerobarrier application: it explains how to record a placement or an assessment, how to consult an occupational standard or the , how to edit a CV or a portfolio, how to search for a tool etc. ...',
      pedagogy6download1: 'Tutorial Zerobarrier EN.pptx',
      pedagogy7title: 'OCCUPATIONAL STANDARDS',
      pedagogy7text: 'The occupational standards are presented in the form of tables and are detailed description of the technical skills to be used in a particular job. There are many different occupational standards. Within the framework of the project, the Soft Skills have been integrated into 7 of them: Cleaning operative (EN, FR), Green area maintenance operative (EN), Viticulture operative (EN, FR), Biotechnology assisstant (EN), Welder/boilermaker ( EN, SP), Seller/restocker (EN, FR), Help cooker (EN FR)',
      pedagogy7download1: 'GAMO EN finalized 22 07 2021 .xlsx',
      pedagogy7download2: 'Help Cooker FR EN finalized.xlsx',
      pedagogy7download3: 'Biotehnology assistant EN finalized 22 07 2021.xlsx',
      pedagogy7download4: 'Cleaning operative FR EN finalized 22 07 2021.xlsx',
      pedagogy7download5: 'Seller Restocker FR EN finalized 22 07 2021.xls',
      pedagogy7download6: 'Viticulture operator FR EN finalized 22 07 2021.xlsx',
      pedagogy7download7: 'Welder Boilermaker SP EN finalized 22 07 2021.xlsx',
      pedagogy8title: 'faltatexto Guide to soft skills in a corporate culture',
      pedagogy8text: 'faltatexto',
      pedagogy8download1: 'faltatexto',
      trainingmaterial1title: 'TRAINING KIT FOR THE IMPLEMENTATION OF SOFT SKILLS',
      trainingmaterial1text: 'The “training kit for the implementation of soft skills” gives all the keys to prepare and implement the soft skills training in any organisation with any trainees. It describes the training method and program in detail and provides summary sheets of training courses by level. It also gives suggestions concerning the pedagogical tools to be used in each step of the training or the posture to adopt as a trainer.  To complete this document, 4 annexes will allow you to implement the proposed activities (Annex 1 – Rules of the Game, Annex 2 – Avatar Cards, Annex 3 – Soft skills Cards, Annex 4- Playing Board.)',
      trainingmaterial1download1: 'Training kit finalized - EN - 30 07 2021.pdf',
      trainingmaterial1download2: 'Annex1-Rules-of-the-game-ENG.pdf',
      trainingmaterial1download3: 'Annex2-Avatar-cards-EN.pdf',
      trainingmaterial1download4: 'Annex3-Soft-Skills-cards-EN.pdf',
      trainingmaterial1download5: 'Annex4-Playing-board-EN.pdf',
      trainingmaterial2title: 'TOOLCARDS TO TRAIN SOFT SKILLS',
      trainingmaterial2text: 'The “tool cards to train soft skills” presents a collection of more than 80 tools that can be used to train soft skills. The tools are based on the experience of the project partners (tools they have learned in their initial training or throughout their professional career, as well as tools developed and/or adapted more specifically for this project). These tools require few equipment and can be easily applied to different contexts. The training kit suggests their use.',
      trainingmaterial2download1: 'TOOLCARDS- finalized - EN - 23 07 2021 .pdf',
      trainingmaterial2download2: 'Annex 2  29. The rock additional material.pdf',
      trainingmaterial2download3: 'Annex 1  28. Lost in the moon additional materials.pdf',
      trainingmaterial3title: 'TRAINING CERTIFICATE FOR TRAINEES',
      trainingmaterial3text: 'At the end of a training for trainees, a trainer should provide a training certificate to each trainee. We propose a model of certificate for each level of Soft Skills to be adapted according to the training followed and the Soft Skills studied',
      trainingmaterial3download1: 'Training certificate - Level 1 - EN.docx',
      trainingmaterial3download2: 'Training certificate - Level 2 - EN.docx',
      trainingmaterial3download3: 'Training certificate - Level 3 EN.docx',
      trainingmaterial3download4: 'Training certificate - level 4 EN.docx',
      trainingmaterial4title: 'ATTENDANCE SHEET',
      trainingmaterial4text: 'It is important to keep track of attendances and absences during a training session: you will find a template of attendance sheet that you can use during a training and complete',
      trainingmaterial4download1: 'Attendance sheet finalized 12 08 EN.xlsx',
      trainingmaterial5title: 'SATISFACTION SURVEYS FOR THE SOFT SKILLS TRAINING OF TRAINEES',
      trainingmaterial5text: 'At the end of the training, these satisfaction surveys can be completed by the trainees and by the trainer; the objective being to question their satisfaction and to improve the training.',
      trainingmaterial5download1: 'Satisfaction survey for training of trainees-EN.doc',
      trainingmaterial6title: 'SOFT SKILLS FACILITATION TECHNIQUES',
      trainingmaterial6text: 'The “facilitation techniques” helps the trainer/ technical supervisor/ tutor/assessor to support their trainees in the consolidation phase in a work situation. It gathers ideas how to put soft skills into practice in the daily work, to act as role models and to advise their trainees.',
      trainingmaterial6download1: 'Facilitation techniques finalized - EN 29 07.pdf',
      trainingmaterial7title: 'SOFT SKILLS TRAINING FOR TRAINERS',
      trainingmaterial7text: 'The “training for trainers” is a program and a training content for trainers, technical supervisors, tutors and assessors who wants learn how to use the project and the tools that result from it and to train in Soft Skills without problems.',
      trainingmaterial7download1: 'Training for trainers - Sl.pdf',
      trainingmaterial8title: 'TRAINING CERTIFICATE FOR TRAINERS',
      trainingmaterial8text: 'At the end of a training for trainers, the trainer should provide a training certificate to each trainer certifying that they know how to use the different materials and that they are ready to train trainees to soft skills. We propose a model of certificate that can be used for that.',
      trainingmaterial8download1: 'Trainning certificate for trainers- Sl.docx',
      trainingmaterial9title: 'VPRAŠALNIK O ZADOVOLJSTVU UČITELJEV',
      trainingmaterial9text: 'Na koncu usposabljanja učitelji izpolnijo vprašalnike o zadovoljstvu. Cilj je preveriti njihovo zadovoljstvo in izboljšati usposabljanje.',
      trainingmaterial9download1: 'Satisfaction survey for training of trainers - SLO.doc',

      trainingmaterial10title: 'Training for tutors/trainers in WBL??? faltatexto',
      trainingmaterial10text: 'faltatexto',
      trainingmaterial10download1: 'faltatexto',

      trainingmaterial11title: 'Training for HRM in WBL??? faltatexto',
      trainingmaterial11text: 'faltatexto',
      trainingmaterial11download1: 'faltatexto',

      assessment1title: 'PROTOKOL UMESTITVE IN OCENJEVANJA',
      assessment1text: 'Protokol umestitve in ocenjevanje mehkih veščin daje napotke za oceno in potrditev usvojitve določene mehke veščine. Opisuje različne metode ocenjevanja ter vključuje orodja za pravilno umestitev in ocenjevanje.',
      assessment1download1: 'placement and assessment protocol Sl.pdf',
      assessment2title: 'SPLOŠNA TABELA ZA UMESTITEV',
      assessment2text: 'Razvili smo splošno tabela za umestitev, ki bo učitelju/supervizorju/mentorju/ocenjevalcu pomagala pri umestitvi, ki ni v povezavi z delovnim mestom. Ta tabela se lahko uporablja za metodo umestitve z opazovanjem, pa tudi za intervju. Sestavljena je iz opredelitev vseh stopenj mehkih veščin v povezavi z izraženim vedenjem in življenjskimi situacijami.',
      assessment2download1: 'Generic placement grid SI finalized 02 08 2021.xlsx',
      assessment3title: 'POSEBNA TABELA ZA UMESTITEV',
      assessment3text: 'Razvitih je bilo sedem posebnih tabel za umestitve, ki učitelju/supervizorju/mentorju/ocenjevalcu pomagajo pri umestitvi v določene poklicne standarde. Te tabele, ki smo jih oblikovali, temeljijo na poklicnih standardih: Čistilec (FR - EN), Varilec kotlov (SP - EN), Vzdrževalec zelenih površin (EN), Prodajalec/Pomočnik v trgovini (FR - EN), Pomočnik kuharja (FR – EN), Delavec v vinogradništvu (FR - EN), Asistent v biotehnologiji (EN).',
      assessment3download1: 'Specific placement grid - Biotechnology assisstant - EN.xlsx',
      assessment3download2: 'Specific placement grid - Cleaning operator - EN.xlsx',
      assessment3download3: 'Specific placement grid - Green areas maintenance operator EN.xlsx',
      assessment3download4: 'Specific placement grid - Seller Restocker EN.xlsx',
      assessment3download5: 'Specific placement grid - Viticulture operator - EN.xlsx',
      assessment3download6: 'Specific placement grid - Assisstant chef - EN.xlsx',
      assessment3download7: 'Specific placement grid - Welder Boilermaker - EN.xlsx',
      assessment4title: 'SPLOŠNA TABELA ZA OCENJEVANJE',
      assessment4text: 'Razvili smo splošno tabelo, ki učitelju/supervizorju/mentorju/ocenjevalcu na koncu procesa usvajanja pomaga oceniti stopnjo mehkih veščin s pomočjo večkratnega opazovanja, kjer delovno opravilo ni povezano z določenim delovnim mestom oz. poklicem. Tabela vključuje izražena vedenja kot kazalnike za oceno, ki potrdi, ali je stopnja mehkih veščin usvojena ali ne.',
      assessment4download1: 'Generic assessment grid SI finalized 02 08 2021.xlsx',
      assessment5title: 'POSEBNA TABELA ZA OCENJEVANJE',
      assessment5text: 'Razvitih je bilo sedem posebnih tabel za ocenjevanje, ki učitelju/supervizorju/mentorju/ocenjevalcu pomagajo oceniti usvojeno stopnjo mehkih veščin udeleženca na koncu usposabljanja. Udeleženca ocenimo tako, da ga večkrat opazujemo v delovni situaciji v povezavi z določenim poklicnim standardom glede na posebne delovne profile: Čistilec (FR - EN), Varilec kotlov (SP - EN), Vzdrževalec zelenih površin (EN), Prodajalec/Pomočnik v trgovini (FR - EN), Pomočnik kuharja (FR – EN), Delavec v vinogradništvu (FR - EN), Asistent v biotehnologiji (EN).',
      assessment5download1: 'Specific assessment grid - Assisstant chef.xlsx',
      assessment5download2: 'Specific assessment grid - Biotechnology assisstant - EN.xlsx',
      assessment5download3: 'Specific assessment grid - Cleaning operator - EN.xlsx',
      assessment5download4: 'Specific assessment grid - Green area maintenance operator - EN.xlsx',
      assessment5download5: 'Specific assessment grid - Seller Restocker - EN.xlsx',
      assessment5download6: 'Specific assessment grid - Viticulture operator - EN.xlsx',
      assessment5download7: 'Specific assessment grid - Welder Boilermaker - EN.xlsx',
      assessment6title: 'KONTROLNI SEZNAM MEHKIH VEŠČIN ZA UČITELJE',
      assessment6text: 'Kontrolni seznam mehkih veščin za učitelje omogoča učiteljem/supervizorjem/mentorjem/ocenjevalcem, da po usposabljanju učiteljev preverijo svoje znanje v zvezi z mehkimi veščinami. Hkrati jim ponuja celosten vpogled v učna gradiva in orodja, ki so potrebna za izvajanje posameznih umestitev, usposabljanj in ocenjevanj mehkih veščin v njihovih organizacijah.',
      assessment6download1: 'Soft skills checklist for Trainers-SI- finalized - 0508..pdf',
      assessment7title: 'faltatexto',
      assessment7text: 'faltatexto',
      assessment7download1: 'Placement and assessment methods for soft skills in WBL situations?????faltatexto',

      humanresources1title: 'HRM Protocol???faltatexto',
      humanresources1text: 'faltatexto',
      humanresources1download1: 'faltatexto',
      // Agrega todas las traducciones
    }
  },
  es: {
    message: {
      subtitle: 'Entrena y desarrolla habilidades blandas',
      paragraph1: '¿Estás interesado en las habilidades blandas y te gustaría integrarlas en tu práctica?',
      paragraph2: 'Las soft skills son habilidades relacionales y humanas cercanas a los rasgos de la personalidad que son esenciales en la vida profesional y que complementan las habilidades y conocimientos especializados (hard skills). Tod@s y cada un@ de nosotr@s las adquirimos parcialmente, independientemente de nuestra trayectoria profesional o personal.',
      paragraph3: 'Sin embargo, hoy en día, la formación en soft skills parece estar orientada de forma más natural a las personas altamente cualificadas.',
      paragraph4: 'El proyecto Erasmus+ "Soft skills" tiene como objetivo facilitar el acceso a las soft skills a las personas con bajo nivel de cualificación y/o con discapacidad, para favorecer su inclusión profesional e incluso social y la igualdad de oportunidades. El dominio de una actividad profesional no sólo requiere la puesta en práctica de habilidades técnicas específicas del trabajo (hard skills), sino que también se basa en las soft skills.',
      paragraph5: 'Nuestro enfoque: tener en cuenta todo el proceso de adquisición de las soft skills. Hemos elaborado numerosos materiales complementarios a los que se puede acceder gratuitamente en este sitio web.',
      paragraph6: 'Además de estos materiales gratuitos, existe una plataforma digital llamada Zerobarrier, a la que se puede acceder bajo cuota. Esta plataforma le permitirá gestionar y seguir el proceso de adquisición de soft skills.',
      button1: 'Informe de medición de impacto',
      subtitle2: '¿Quiénes somos?',
      partners: 'Es en el marco del proyecto europeo "Soft Skills" cofinanciado por el programa Erasmus +, que 9 socios europeos de Francia, Bélgica, España, Austria y Eslovenia han co desarrollado los materiales que encontrarás en esta web. Estos socios trabajan en el ámbito de la formación profesional. Ya sean centros de formación, empresas de integración o empresas adaptadas, tienen experiencia en la formación de personas con un bajo nivel de cualificación y/o una discapacidad. Haga clic en los logotipos para saber más sobre ellos.',

      // Agrega todas las traducciones
    }
  },
  fr: {
    message: {
      subtitle: 'Former et développer les soft skills',
      paragraph1: 'Vous êtes intéressé par les Soft Skills et vous souhaitez les intégrer dans votre pratique ?',
      paragraph2: 'Les Soft Skills sont des compétences relationnelles et humaines proches des traits de personnalité qui sont essentielles dans la vie professionnelle et qui viennent en complément des compétences et savoirs spécialisés (Hard Skills). Chacun d\'entre nous les acquiert partiellement, quel que soit son parcours professionnel ou personnel.',
      paragraph3: 'Aujourd\'hui, cependant, la formation aux Soft Skills semble s\'adresser plus naturellement aux personnes hautement qualifiées.',
      paragraph4: 'Le projet Erasmus+ "Soft skills" vise à faciliter l\'accès aux soft skills pour les personnes à faible niveau de qualification et/ou en situation de handicap, afin de favoriser leur insertion professionnelle, sociale et l\'égalité des chances. La maîtrise d\'une activité professionnelle ne nécessite pas seulement la mise en œuvre de compétences techniques spécifiques à l\'emploi (hard skills), elle s\'appuie également sur des soft skills.',
      paragraph5: 'Notre approche : prendre en compte l\'ensemble du process d\'acquisition des Soft Skills en developpant de nombreux supports complémentaires et accessibles gratuitement sur ce site.',
      paragraph6: 'En plus de ces supports gratuits, une plateforme numérique appelée Zerobarrier, accessible contre paiement, est mobilisable. Cette plateforme vous permettra de gérer et de suivre le process d\'acquisition des Soft Skills.',
      button1: 'Impact measurement report-VF.pdf',
      subtitle2: 'Qui sommes-nous?',
      partners: 'C\'est dans le cadre du projet européen "Soft Skills" cofinancé par le programme Erasmus +, que 9 partenaires européens de France, Belgique, Espagne, Autriche et Slovénie ont co-construits les supports que vous trouverez sur ce site. Ces partenaires sont actifs dans le domaine de la formation professionnelle : qu\'il s\'agisse de centres de formation, d\'entreprises d\'insertion ou d\'entreprises adaptées, ils ont tous une expertise dans la formation des personnes ayant un faible niveau de qualification et/ou en situation de handicap. Cliquez sur les logos pour en savoir plus sur eux.',
      pedagogy1title: 'CATALOGUE EUROPÉEN DES RÉFÉRENCES SOFT SKILLS',
      pedagogy1text: 'Le catalogue européen de références soft skills donne une vue d\'ensemble de l\'approche suivie par le projet : il contient la liste des soft skills définis dans le cadre du projet, les niveaux d\'acquisition et leurs définitions ainsi qu\'une description du processus d\'acquisition des soft skills et du positionnement et de l\'évaluation qui y sont liés.',
      pedagogy1download1: 'Catalogue FR.pdf',
      pedagogy2title: 'LISTE DES SOFT SKILLS AVEC PICTOGRAMMES',
      pedagogy2text: 'Ce document illustre les 5 catégories et les 20 soft skills définis dans le projet à l\'aide de pictogrammes. Un bon document de communication et un bon support pédagogique pour mémoriser et retenir les soft skills et leurs définitions.',
      pedagogy2download1: 'Soft skills list with pictograms FR finalized 16 07 21.pdf',
      pedagogy3title: 'SOFT SKILLS BASE',
      pedagogy3text: 'The Soft Skills base is a document that brings together in a table all the definitions of the categories and Soft Skills by level as well as the observable behaviours and life situations that are related to them.',
      pedagogy3download1: 'Soft skills base 27 07 2021 - finalized EN.xlsx',
      pedagogy4title: 'WHEELS',
      pedagogy4text: 'This document illustrates the 5 categories and the 20 soft skills defined in the project using wheels. These wheels are a good way to visualize your level of soft skills and can be used during a placement or an Assessment.',
      pedagogy4download1: 'Wheels EN finalized 16 07 2021.pdf',
      pedagogy5title: 'SUMMARY OF THE SOFT SKILLS ACQUISITION PROCESS',
      pedagogy5text: 'This sheet gives an overview of the 3 steps of the Soft Skills acquisition process as well as the tools that can be used at each step. It will help the trainer to keep in mind all the elements that will be useful and to look at the process in its entirety',
      pedagogy5download1: 'Summary of the project EN.pdf',
      pedagogy6title: 'ZEROBARRIER MANUAL',
      pedagogy6text: 'Manual that explains how to use the Zerobarrier application: it explains how to record a placement or an assessment, how to consult an occupational standard or the , how to edit a CV or a portfolio, how to search for a tool etc. ...',
      pedagogy6download1: 'Tutorial Zerobarrier EN.pptx',
      pedagogy7title: 'OCCUPATIONAL STANDARDS',
      pedagogy7text: 'The occupational standards are presented in the form of tables and are detailed description of the technical skills to be used in a particular job. There are many different occupational standards. Within the framework of the project, the Soft Skills have been integrated into 7 of them: Cleaning operative (EN, FR), Green area maintenance operative (EN), Viticulture operative (EN, FR), Biotechnology assisstant (EN), Welder/boilermaker ( EN, SP), Seller/restocker (EN, FR), Help cooker (EN FR)',
      pedagogy7download1: 'GAMO EN finalized 22 07 2021 .xlsx',
      pedagogy7download2: 'Help Cooker FR EN finalized.xlsx',
      pedagogy7download3: 'Biotehnology assistant EN finalized 22 07 2021.xlsx',
      pedagogy7download4: 'Cleaning operative FR EN finalized 22 07 2021.xlsx',
      pedagogy7download5: 'Seller Restocker FR EN finalized 22 07 2021.xls',
      pedagogy7download6: 'Viticulture operator FR EN finalized 22 07 2021.xlsx',
      pedagogy7download7: 'Welder Boilermaker SP EN finalized 22 07 2021.xlsx',
      pedagogy8title: 'faltatexto Guide to soft skills in a corporate culture',
      pedagogy8text: 'faltatexto',
      pedagogy8download1: 'faltatexto',
      trainingmaterial1title: 'TRAINING KIT FOR THE IMPLEMENTATION OF SOFT SKILLS',
      trainingmaterial1text: 'The “training kit for the implementation of soft skills” gives all the keys to prepare and implement the soft skills training in any organisation with any trainees. It describes the training method and program in detail and provides summary sheets of training courses by level. It also gives suggestions concerning the pedagogical tools to be used in each step of the training or the posture to adopt as a trainer.  To complete this document, 4 annexes will allow you to implement the proposed activities (Annex 1 – Rules of the Game, Annex 2 – Avatar Cards, Annex 3 – Soft skills Cards, Annex 4- Playing Board.)',
      trainingmaterial1download1: 'Training kit finalized - EN - 30 07 2021.pdf',
      trainingmaterial1download2: 'Annex1-Rules-of-the-game-ENG.pdf',
      trainingmaterial1download3: 'Annex2-Avatar-cards-EN.pdf',
      trainingmaterial1download4: 'Annex3-Soft-Skills-cards-EN.pdf',
      trainingmaterial1download5: 'Annex4-Playing-board-EN.pdf',
      trainingmaterial2title: 'TOOLCARDS TO TRAIN SOFT SKILLS',
      trainingmaterial2text: 'The “tool cards to train soft skills” presents a collection of more than 80 tools that can be used to train soft skills. The tools are based on the experience of the project partners (tools they have learned in their initial training or throughout their professional career, as well as tools developed and/or adapted more specifically for this project). These tools require few equipment and can be easily applied to different contexts. The training kit suggests their use.',
      trainingmaterial2download1: 'TOOLCARDS- finalized - EN - 23 07 2021 .pdf',
      trainingmaterial2download2: 'Annex 2  29. The rock additional material.pdf',
      trainingmaterial2download3: 'Annex 1  28. Lost in the moon additional materials.pdf',
      trainingmaterial3title: 'TRAINING CERTIFICATE FOR TRAINEES',
      trainingmaterial3text: 'At the end of a training for trainees, a trainer should provide a training certificate to each trainee. We propose a model of certificate for each level of Soft Skills to be adapted according to the training followed and the Soft Skills studied',
      trainingmaterial3download1: 'Training certificate - Level 1 - EN.docx',
      trainingmaterial3download2: 'Training certificate - Level 2 - EN.docx',
      trainingmaterial3download3: 'Training certificate - Level 3 EN.docx',
      trainingmaterial3download4: 'Training certificate - level 4 EN.docx',
      trainingmaterial4title: 'ATTENDANCE SHEET',
      trainingmaterial4text: 'It is important to keep track of attendances and absences during a training session: you will find a template of attendance sheet that you can use during a training and complete',
      trainingmaterial4download1: 'Attendance sheet finalized 12 08 EN.xlsx',
      trainingmaterial5title: 'SATISFACTION SURVEYS FOR THE SOFT SKILLS TRAINING OF TRAINEES',
      trainingmaterial5text: 'At the end of the training, these satisfaction surveys can be completed by the trainees and by the trainer; the objective being to question their satisfaction and to improve the training.',
      trainingmaterial5download1: 'Satisfaction survey for training of trainees-EN.doc',
      trainingmaterial6title: 'SOFT SKILLS FACILITATION TECHNIQUES',
      trainingmaterial6text: 'The “facilitation techniques” helps the trainer/ technical supervisor/ tutor/assessor to support their trainees in the consolidation phase in a work situation. It gathers ideas how to put soft skills into practice in the daily work, to act as role models and to advise their trainees.',
      trainingmaterial6download1: 'Facilitation techniques finalized - EN 29 07.pdf',
      trainingmaterial7title: 'SOFT SKILLS TRAINING FOR TRAINERS',
      trainingmaterial7text: 'The “training for trainers” is a program and a training content for trainers, technical supervisors, tutors and assessors who wants learn how to use the project and the tools that result from it and to train in Soft Skills without problems.',
      trainingmaterial7download1: 'Training for trainers - Sl.pdf',
      trainingmaterial8title: 'TRAINING CERTIFICATE FOR TRAINERS',
      trainingmaterial8text: 'At the end of a training for trainers, the trainer should provide a training certificate to each trainer certifying that they know how to use the different materials and that they are ready to train trainees to soft skills. We propose a model of certificate that can be used for that.',
      trainingmaterial8download1: 'Trainning certificate for trainers- Sl.docx',
      trainingmaterial9title: 'VPRAŠALNIK O ZADOVOLJSTVU UČITELJEV',
      trainingmaterial9text: 'Na koncu usposabljanja učitelji izpolnijo vprašalnike o zadovoljstvu. Cilj je preveriti njihovo zadovoljstvo in izboljšati usposabljanje.',
      trainingmaterial9download1: 'Satisfaction survey for training of trainers - SLO.doc',

      trainingmaterial10title: 'Training for tutors/trainers in WBL??? faltatexto',
      trainingmaterial10text: 'faltatexto',
      trainingmaterial10download1: 'faltatexto',

      trainingmaterial11title: 'Training for HRM in WBL??? faltatexto',
      trainingmaterial11text: 'faltatexto',
      trainingmaterial11download1: 'faltatexto',

      assessment1title: 'PROTOKOL UMESTITVE IN OCENJEVANJA',
      assessment1text: 'Protokol umestitve in ocenjevanje mehkih veščin daje napotke za oceno in potrditev usvojitve določene mehke veščine. Opisuje različne metode ocenjevanja ter vključuje orodja za pravilno umestitev in ocenjevanje.',
      assessment1download1: 'placement and assessment protocol Sl.pdf',
      assessment2title: 'SPLOŠNA TABELA ZA UMESTITEV',
      assessment2text: 'Razvili smo splošno tabela za umestitev, ki bo učitelju/supervizorju/mentorju/ocenjevalcu pomagala pri umestitvi, ki ni v povezavi z delovnim mestom. Ta tabela se lahko uporablja za metodo umestitve z opazovanjem, pa tudi za intervju. Sestavljena je iz opredelitev vseh stopenj mehkih veščin v povezavi z izraženim vedenjem in življenjskimi situacijami.',
      assessment2download1: 'Generic placement grid SI finalized 02 08 2021.xlsx',
      assessment3title: 'POSEBNA TABELA ZA UMESTITEV',
      assessment3text: 'Razvitih je bilo sedem posebnih tabel za umestitve, ki učitelju/supervizorju/mentorju/ocenjevalcu pomagajo pri umestitvi v določene poklicne standarde. Te tabele, ki smo jih oblikovali, temeljijo na poklicnih standardih: Čistilec (FR - EN), Varilec kotlov (SP - EN), Vzdrževalec zelenih površin (EN), Prodajalec/Pomočnik v trgovini (FR - EN), Pomočnik kuharja (FR – EN), Delavec v vinogradništvu (FR - EN), Asistent v biotehnologiji (EN).',
      assessment3download1: 'Specific placement grid - Biotechnology assisstant - EN.xlsx',
      assessment3download2: 'Specific placement grid - Cleaning operator - EN.xlsx',
      assessment3download3: 'Specific placement grid - Green areas maintenance operator EN.xlsx',
      assessment3download4: 'Specific placement grid - Seller Restocker EN.xlsx',
      assessment3download5: 'Specific placement grid - Viticulture operator - EN.xlsx',
      assessment3download6: 'Specific placement grid - Assisstant chef - EN.xlsx',
      assessment3download7: 'Specific placement grid - Welder Boilermaker - EN.xlsx',
      assessment4title: 'SPLOŠNA TABELA ZA OCENJEVANJE',
      assessment4text: 'Razvili smo splošno tabelo, ki učitelju/supervizorju/mentorju/ocenjevalcu na koncu procesa usvajanja pomaga oceniti stopnjo mehkih veščin s pomočjo večkratnega opazovanja, kjer delovno opravilo ni povezano z določenim delovnim mestom oz. poklicem. Tabela vključuje izražena vedenja kot kazalnike za oceno, ki potrdi, ali je stopnja mehkih veščin usvojena ali ne.',
      assessment4download1: 'Generic assessment grid SI finalized 02 08 2021.xlsx',
      assessment5title: 'POSEBNA TABELA ZA OCENJEVANJE',
      assessment5text: 'Razvitih je bilo sedem posebnih tabel za ocenjevanje, ki učitelju/supervizorju/mentorju/ocenjevalcu pomagajo oceniti usvojeno stopnjo mehkih veščin udeleženca na koncu usposabljanja. Udeleženca ocenimo tako, da ga večkrat opazujemo v delovni situaciji v povezavi z določenim poklicnim standardom glede na posebne delovne profile: Čistilec (FR - EN), Varilec kotlov (SP - EN), Vzdrževalec zelenih površin (EN), Prodajalec/Pomočnik v trgovini (FR - EN), Pomočnik kuharja (FR – EN), Delavec v vinogradništvu (FR - EN), Asistent v biotehnologiji (EN).',
      assessment5download1: 'Specific assessment grid - Assisstant chef.xlsx',
      assessment5download2: 'Specific assessment grid - Biotechnology assisstant - EN.xlsx',
      assessment5download3: 'Specific assessment grid - Cleaning operator - EN.xlsx',
      assessment5download4: 'Specific assessment grid - Green area maintenance operator - EN.xlsx',
      assessment5download5: 'Specific assessment grid - Seller Restocker - EN.xlsx',
      assessment5download6: 'Specific assessment grid - Viticulture operator - EN.xlsx',
      assessment5download7: 'Specific assessment grid - Welder Boilermaker - EN.xlsx',
      assessment6title: 'KONTROLNI SEZNAM MEHKIH VEŠČIN ZA UČITELJE',
      assessment6text: 'Kontrolni seznam mehkih veščin za učitelje omogoča učiteljem/supervizorjem/mentorjem/ocenjevalcem, da po usposabljanju učiteljev preverijo svoje znanje v zvezi z mehkimi veščinami. Hkrati jim ponuja celosten vpogled v učna gradiva in orodja, ki so potrebna za izvajanje posameznih umestitev, usposabljanj in ocenjevanj mehkih veščin v njihovih organizacijah.',
      assessment6download1: 'Soft skills checklist for Trainers-SI- finalized - 0508..pdf',
      assessment7title: 'faltatexto',
      assessment7text: 'faltatexto',
      assessment7download1: 'Placement and assessment methods for soft skills in WBL situations?????faltatexto',

      humanresources1title: 'HRM Protocol???faltatexto',
      humanresources1text: 'faltatexto',
      humanresources1download1: 'faltatexto',
      // Agrega todas las traducciones
    }
  },
  de: {
    message: {
      subtitle: 'Soft Skills trainieren und weiterentwickeln',
      paragraph1: 'Sie interessieren sich für Soft Skills und möchten diese in Ihre Praxis integrieren?',
      paragraph2: 'Soft Skills sind soziale und personale Kompetenzen, die den Persönlichkeitsmerkmalen nahekommen, im Berufsleben unverzichtbar sind und die die fachlichen Fähigkeiten und Kenntnisse (Hard Skills) ergänzen. Jede/r von uns erwirbt sie bis zu einem gewissen Grad unabhängig von seinem beruflichen oder persönlichen Hintergrund. Heutzutage hat man jedoch den Eindruck, dass sich Angebote für Soft Skills Schulungen ganz selbstverständlich vor allem an hochqualifizierte Menschen richten.',
      paragraph3: 'Das Erasmus+ Projekt "Soft Skills" zielt darauf ab, den Zugang zu Soft Skills für Menschen mit niedrigem Qualifikationsniveau und/oder mit Behinderungen zu erleichtern, um ihre berufliche und sogar soziale Integration und Chancengleichheit zu fördern. Die Bewältigung einer beruflichen Tätigkeit erfordert nicht nur die Umsetzung von berufsspezifischen technischen Fähigkeiten (Hard Skills), sondern ist auch auf Soft Skills angewiesen.',
      paragraph4: '',
      paragraph5: 'Dabei wurde der Ansatz verfolgt, den gesamten Erwerbsprozess von Soft Skills zu berücksichtigen. Dazu wurden zahlreiche ergänzende Materialien entwickelt, die auf dieser Website kostenfrei zugänglich sind.',
      paragraph6: 'Zusätzlich zu diesen kostenlosen Materialien ist die digitale Plattform Zerobarrier gegen eine Gebühr zugänglich. Diese Plattform ermöglicht es Ihnen, den Erwerbsprozess von Soft Skills für Teilnehmer/innen online zu verwalten und zu dokumentieren.',
      button1: 'Bericht zur Wirkungsmessung',
      subtitle2: 'Wer sind die Partner-Organisationen?',
      partners: 'Im Rahmen des europäischen Projekts "Soft skills", das durch das Erasmus+ Programm kofinanziert wird, haben neun europäische Partnerorganisationen aus Frankreich, Belgien, Spanien, Österreich und Slowenien gemeinsam die Materialien entwickelt, die Sie auf dieser Website finden. Alle Partnerorganisationen sind im Bereich der beruflichen Bildung tätig. Egal, ob es sich um Ausbildungszentren, Integrationsfirmen oder sozialökonomische Betriebe handelt, sie haben Expertise in der Ausbildung von niedrig-qualifizierten Personen und/oder Menschen mit Behinderungen. Klicken Sie auf die Logos, um mehr über die Organisationen zu erfahren.',

      // Agrega todas las traducciones
    }
  },
  sl: {
    message: {
      subtitle: 'Usvajajte in razvijajte mehke veščine',
      paragraph1: 'Vas zanimajo mehke veščine in bi jih radi vključili v svoje delo in prakso?',
      paragraph2: 'Mehke veščine so medosebne in človeške veščine, ki so povezane z osebnostnimi lastnostmi posameznika. Zelo pomembne so v poklicnem življenju in dopolnjujejo posebne, določene veščine in znanja (trde veščine). Vsak od nas mehke veščine v življenju ves čas bolj ali manj pridobiva, ne glede na svojo poklicno ali osebno pot.',
      paragraph3: 'V današnjem času je vse bolj jasno, da je pridobivanje mehkih veščin zelo pomemben in obenem naraven proces v doseganju ciljev za čim višjo usposobljenost vsakega izmed nas.',
      paragraph4: 'Namen projekta Erasmus + «Soft Skills» (mehke veščine) je olajšati dostop do učenja in usvajanja mehkih veščin posameznikov z nižjo stopnjo izobrazbe in / ali invalidov. Glavni cilj je spodbuditi njihovo poklicno in socialno vključenost ter enake možnosti za vključevanje na različna področja družbenega življenja. Obvladovanje določenih poklicnih dejavnosti ne zahteva le izvajanje določenih tehničnih veščin, ki so specifične za posamezno delovno mesto (trde veščine), temveč vključuje tudi obvladovanje mehkih veščin, ki jih ima posameznik usvojene do določene mere in jih lahko ves čas uspešno razvija.',
      paragraph5: 'Naš pristop in ponujene možnosti usposabljanja mehkih veščin vključujejo celoten postopek v procesu učenja in pridobivanja mehkih veščin s posameznimi koraki napredovanja znotraj 4 stopenj zahtevnosti. Razvili smo številna učna gradiva in pripomočke za pomoč in uspešno učenje. Na tej spletni strani so dostopni brezplačno.',
      paragraph6: 'Poleg omenjenih brezplačnih gradiv je za doplačilo na voljo tudi digitalna platforma z imenom Zerobarrier. Ta platforma omogoča celotno usposabljanje in smernice v procesu učenja in usvajanja mehkih veščin, spremljanje napredka udeležencev usposabljanja in evalvacijo za vse vključene v celotnem postopku usposabljanja in usvajanja mehkih veščin.',
      button1: 'Impact measurement report-EN.pdf',
      subtitle2: 'Kdo smo?',
      partners: 'V okviru evropskega projekta "Soft Skills", ki je sofinanciran s strani programa Erasmus +, je 9 evropskih partnerjev iz Francije, Belgije, Španije, Avstrije in Slovenije soustvarjalo in razvilo zelo uporabna učna gradiva z učnimi sredstvi in pripomočki, ki jih boste našli na tej spletni strani. Velikega pomena je, da so partnerji dejavni na področju poklicnega usposabljanja in poznajo posebnosti učenja oseb z nižjimi poklicnimi kvalifikacijami in nižjim izobrazbenim standardom. Ne glede na to, ali gre za izobraževalne centre, integracijska podjetja ali organizacije za usposabljanje in rehabilitacijo, so partnerji projekta strokovnjaki in kompetentni na področju usposabljanju oseb z nižjo stopnjo izobrazbe in / ali invalidnostjo. Če želite izvedeti več o njih, kliknite na njihove logotipe. ',
      pedagogy1title: 'EVROPSKI KATALOG REFERENC MEHKIH VEŠČIN',
      pedagogy1text: '"Evropski katalog referenc mehkih veščin" daje pregled k pristopu mehkih veščin, ki smo jih razvijali v projektu. Vsebuje seznam mehkih veščin, opredeljenih v okviru projekta, stopnje usvajanja mehkih veščin in njihove opredelitve ter opis postopka usvajanja mehkih veščin in s tem povezanih umestitev in ocenjevanja.',
      pedagogy1download1: 'KATALOG Sl .pdf',
      pedagogy2title: 'LIST MEHKIH VEŠČIN S PIKTOGRAMI',
      pedagogy2text: 'Ta dokument ponazarja 5 kategorij in 20 mehkih veščin, opredeljenih v projektu s piktogrami. Dokument nam omogoča učinkovito komunikacijo in dobro učno podporo za lažje pomnenje in ohranjanje usvojenih mehkih veščin ter njihovih opredelitev.',
      pedagogy2download1: 'Soft skills list with pictograms_SI finalized 16_07_21.pdf',
      pedagogy3title: 'BAZA MEHKIH VEŠČIN',
      pedagogy3text: 'Baza mehkih veščin je dokument, ki v tabeli združuje vse definicije kategorij in mehkih veščin po stopnjah ter izraženo vedenje in življenjske situacije, ki so z njimi povezane.',
      pedagogy3download1: 'Soft skills base - 27 07 2021 - finalized - Sl.xlsx',
      pedagogy4title: 'KOLESA',
      pedagogy4text: 'Dokument Kolesa ponazarja 5 kategorij in 20 mehkih veščin, ki smo jih opredelili v projektu. Ta kolesa so dober način za prikaz določene stopnje mehkih veščin in jih lahko uporabite v postopku umestitve ali ocenjevanja.',
      pedagogy4download1: 'Wheels SI finalized 16 07 2021 .pdf',
      pedagogy5title: 'POVZETEK PROCESA USVAJANJA MEHKIH VEŠČIN',
      pedagogy5text: 'Predstavljen je pregled 3 korakov v procesu usvajanja mehkih veščin in orodij, ki jih je mogoče uporabiti pri tem uporabiti. Učitelju bo v pomoč, da bo lahko upošteval vse elemente, ki so pomembni za izvedbo celotnega procesa.',
      pedagogy5download1: 'summary of the project- SLO.pdf',
      pedagogy6title: 'PRIROČNIK ZEROBARRIER',
      pedagogy6text: 'Priročnik pojasnjuje, kako uporabljati aplikacijo Zerobarrier: kako zabeležiti umestitev ali oceno, kako poiskati povezavo z določenim poklicnim standardom, kako urediti življenjepis ali zbirno mapo (portfolio), kako iskati orodje itd.',
      pedagogy6download1: 'Tutorial Zerobarrier EN.pptx',
      pedagogy7title: 'POKLICNI STANDARDI',
      pedagogy7text: 'Poklicni standardi so predstavljeni v obliki tabel in podrobno opisujejo tehnične sposobnosti, ki jih je treba uporabiti na določenem delovnem mestu. Obstaja veliko različnih poklicnih standardov. V okviru projekta so bile mehke veščine vključene v 7 poklicnih standardov: Čistilec (EN, FR), Vzdrževalec zelenih površin (EN), Delavec v vinogradništvu (EN, FR), Pomočnik kuharja (EN), Varilec kotlov (EN, SP), Prodajalec/Pomočnik v trgovini (EN, FR), Asistent v biotehnologiji (EN FR).',
      pedagogy7download1: 'GAMO EN finalized 22 07 2021 .xlsx',
      pedagogy7download2: 'Help Cooker FR EN finalized.xlsx',
      pedagogy7download3: 'Biotehnology assistant EN finalized 22 07 2021.xlsx',
      pedagogy7download4: 'Cleaning operative FR EN finalized 22 07 2021.xlsx',
      pedagogy7download5: 'Seller Restocker FR EN finalized 22 07 2021.xls',
      pedagogy7download6: 'Viticulture operator FR EN finalized 22 07 2021.xlsx',
      pedagogy7download7: 'Welder Boilermaker SP EN finalized 22 07 2021.xlsx',
      pedagogy8title: 'faltatexto Guide to soft skills in a corporate culture',
      pedagogy8text: 'faltatexto',
      pedagogy8download1: 'faltatexto',
      trainingmaterial1title: 'KOMPLET UČNIH GRADIV ZA USPOSABLJANJE MEHKIH VEŠČIN',
      trainingmaterial1text: '"Komplet učnih gradiv za usposabljanje mehkih veščin" daje vse ključne informacije za pripravo in izvajanje usposabljanja mehkih veščin v različnih organizacijah z različnimi udeleženci. Podrobno opisuje način in program usposabljanja. Vsebuje tudi povzetek učnih gradiv za usposabljanje po posameznih stopnjah. Ponuja tudi predloge v zvezi z učnimi orodji, ki jih je mogoče uporabiti v vsakem koraku usposabljanja in priporočila za učitelja. Za uspešno izvajanje usposabljanja vam bodo v pomoč 4 priloge, ki omogočajo izvajanje predlaganih dejavnosti (Priloga 1 - Pravila igre, Priloga 2 - Karte »Avatar«, Priloga 3- Karte mehkih veščin, Priloga 4 - Igralna tabla/predloga)',
      trainingmaterial1download1: 'Training kit SLO.pdf',
      trainingmaterial1download2: 'Annex1- Rules of the game-SLO.pdf',
      trainingmaterial1download3: 'Annex2-Avatar-cards - SLO.pdf',
      trainingmaterial1download4: 'Annex3-Soft-Skills-cards-SLO.pdf',
      trainingmaterial1download5: 'Annex4-Playing-board – SLO.pdf',
      trainingmaterial2title: 'UČNE KARTE ZA USPOSABLJANJE MEHKIH VEŠČIN',
      trainingmaterial2text: 'Učne karte za usposabljanje mehkih veščin predstavljajo zbirko več kot 80 orodij, ki jih je mogoče uporabiti za usposabljanje mehkih veščin. Orodja temeljijo na izkušnjah projektnih partnerjev (orodja, ki so se jih naučili uporabljati pri začetnem usposabljanju ali v svoji poklicni karieri, pa tudi orodja, razvita in/ali prilagojena posebej za ta projekt). Ta orodja zahtevajo malo opreme in jih je mogoče enostavno uporabiti v različnih kontekstih. Komplet učnih gradiv za usposabljanje predlaga njihovo uporabo.',
      trainingmaterial2download1: 'TOOLCARDS- finalized - 01 09 2021 SI.pdf',
      trainingmaterial2download2: 'Annex 2  29. The rock additional material.pdf',
      trainingmaterial2download3: 'Annex 1  28. Lost in the moon additional materials.pdf',
      trainingmaterial3title: 'POTRDILO O USPOSABLJANJU',
      trainingmaterial3text: 'Na koncu usposabljanja za udeležence učitelj vsakemu udeležencu predloži potrdilo o usposabljanju. Za vsako stopnjo usvojenih mehkih veščin predlagamo obliko potrdila, ki ga  prilagodimo glede na stopnje usposabljanja in usvojene mehke veščine.',
      trainingmaterial3download1: 'Training certificate - Level 1 - Sl.docx',
      trainingmaterial3download2: 'Training certificate - Level 2 - Sl.docx',
      trainingmaterial3download3: 'Training certificate - Level 3 Sl.docx',
      trainingmaterial3download4: 'Training certificate - Level 4 Sl.docx',
      trainingmaterial4title: 'LISTA PRISOTNOSTI',
      trainingmaterial4text: 'Pomembno je, da med usposabljanjem beležimo prisotnost in odsotnost udeležencev: priložen je obrazec liste prisotnosti za udeležbo.',
      trainingmaterial4download1: 'attendance sheet-SLO - 12 08.xlsx',
      trainingmaterial5title: 'VPRAŠALNIK ZADOVOLJSTVA ZA UDELEŽENCE',
      trainingmaterial5text: 'Na koncu usposabljanja udeleženci izpolnijo vprašalnike o zadovoljstvu. Cilj je preveriti njihovo zadovoljstvo in izboljšati usposabljanje.',
      trainingmaterial5download1: 'Satisfaction survey for training of trainees - SLO.doc',
      trainingmaterial6title: 'PODPORNE TEHNIKE',
      trainingmaterial6text: '"Podporne tehnike « pomagajo učitelju/ supervizorju/ mentorju/ocenjevalcu pri podpori udeležencem v fazi utrjevanja mehkih veščin v delovni situaciji, biti zgled in svetovalec svojim udeležencem. So zbirka idej, kako mehke veščine uporabiti pri vsakodnevnem delu.',
      trainingmaterial6download1: 'Facilitation techniques finalized - EN 29 07.pdf',
      trainingmaterial7title: 'USPOSABLJANJE MEHKIH VEŠČIN ZA UČITELJE',
      trainingmaterial7text: 'Usposabljanje za učitelje/supervizorje/mentorje/ocenjevalce vključuje program usposabljanja in učne vsebine s ciljem, da se naučijo uporabljati učno gradivo - metodo in orodja za usposabljanje mehkih veščin.',
      trainingmaterial7download1: 'Trainning certificate for trainers- Sl.docx',
      trainingmaterial8title: 'POTRDILO O USPOSABLJANJU ZA UDELEŽENCE',
      trainingmaterial8text: 'Na koncu usposabljanja učitelj vsakemu udeležencu predloži potrdilo o usposabljanju, ki potrjuje, da zna uporabljati metodo in različna orodja ter da je usposobljen za usposabljanje mehkih veščin. Predlagamo obliko potrdila, ki ga lahko uporabite.',
      trainingmaterial8download1: 'Trainning certificate for trainers- Sl.docx',
      trainingmaterial9title: 'SATISFACTION SURVEY FOR THE SOFT SKILLS TRAINING OF TRAINERS',
      trainingmaterial9text: 'At the end of the training, these satisfaction surveys can be completed by the trainers who followed the training and by the trainer who provided the training; the objective being to question their satisfaction and to improve the training',
      trainingmaterial9download1: 'Satisfaction survey for training of trainers - EN.doc',

      trainingmaterial10title: 'Training for tutors/trainers in WBL??? faltatexto',
      trainingmaterial10text: 'faltatexto',
      trainingmaterial10download1: 'faltatexto',

      trainingmaterial11title: 'Training for HRM in WBL??? faltatexto',
      trainingmaterial11text: 'faltatexto',
      trainingmaterial11download1: 'faltatexto',

      assessment1title: 'SOFT SKILLS PLACEMENT AND ASSESSMENT PROTOCOL',
      assessment1text: 'The “soft skills placement and assessment protocol” gives you all the keys to assess and attest the acquisition of a soft skill. It describes the different moments and methods of assessment and gives you tools to do the placement and assessment properly.',
      assessment1download1: 'Placement and assessment protocol EN 04 08 2021.pdf',
      assessment2title: 'GENERIC PLACEMENT GRID',
      assessment2text: 'A generic placement grid has been developed and will help the trainer/ technical supervisor/ tutor/ assessor to do a not job-related placement. This grid can be used for the placement method by observation but also for the interview and is composed of all soft skills level definitions linked to observable behaviours and life situations',
      assessment2download1: 'Generic placement grid EN finalized 02 08 2021.xlsx',
      assessment3title: 'SPECIFIC PLACEMENT GRIDS',
      assessment3text: 'Seven specific placement grids have been developed and helps the trainer/ technical supervisor/ tutor/ assessor to do a job-related placement. These grids are based on occupational standards we worked on: Cleaning operative (FR – EN), Welder Boilermaker (SP – EN), Green Area Maintenance operator (EN), Seller Restocker (FR – EN), Help Cooker (FR – EN), Viticulture operator (FR – EN), Biotechnology assistant (EN)',
      assessment3download1: 'Specific placement grid - Biotechnology assisstant - EN.xlsx',
      assessment3download2: 'Specific placement grid - Cleaning operator - EN.xlsx',
      assessment3download3: 'Specific placement grid - Green areas maintenance operator EN.xlsx',
      assessment3download4: 'Specific placement grid - Seller Restocker EN.xlsx',
      assessment3download5: 'Specific placement grid - Viticulture operator - EN.xlsx',
      assessment3download6: 'Specific placement grid - Assisstant chef - EN.xlsx',
      assessment3download7: 'Specific placement grid - Welder Boilermaker - EN.xlsx',
      assessment4title: 'GENERIC ASSESSMENT GRID',
      assessment4text: 'A generic assessment grid has been developed and helps the trainer/ technical supervisor/ tutor/ assessor to assess soft skills level at the end of an acquisition process by using the evaluation by recurrent observation method without link with a precise job. As the placement grid, it uses the observable behaviours as indicators to attest if a soft skills level is acquired or not.',
      assessment4download1: 'Generic assessment grid EN finalized 02 08 2021.xlsx',
      assessment5title: 'SPECIFIC ASSESSMENT GRID BIOTECHNOLOGY ASSISTANT',
      assessment5text: 'Seven specific assessment grids have been developed and helps the trainer/ technical supervisor/ tutor/ assessor to assess the level of soft skills of a trainee at the end of an acquisition process by using the method of assessment by recurrent observation in relation to specific job profiles : Cleaning operative (FR – EN), Welder Boilermaker (SP – EN), Green Area Maintenance operator (EN), Seller Restocker (FR – EN), Help Cooker (FR – EN), Viticulture operator (FR – EN), Biotechnology assistant (EN)',
      assessment5download1: 'Specific assessment grid - Assisstant chef.xlsx',
      assessment5download2: 'Specific assessment grid - Biotechnology assisstant - EN.xlsx',
      assessment5download3: 'Specific assessment grid - Cleaning operator - EN.xlsx',
      assessment5download4: 'Specific assessment grid - Green area maintenance operator - EN.xlsx',
      assessment5download5: 'Specific assessment grid - Seller Restocker - EN.xlsx',
      assessment5download6: 'Specific assessment grid - Viticulture operator - EN.xlsx',
      assessment5download7: 'Specific assessment grid - Welder Boilermaker - EN.xlsx',
      assessment6title: 'SOFT SKILLS CHECKLIST FOR TRAINERS',
      assessment6text: 'The “soft skills checklist for trainers” allows trainers, technical supervisors, tutors and assessors to verify their knowledge related to soft skills after a training of trainers but also to have a global view on the materials and tools necessary for the implementation of placements, trainings or soft skills assessments within their organization.',
      assessment6download1: 'Soft skills checklist for Trainers-EN- finalized - 05 08 2021.pdf',
      assessment7title: 'faltatexto',
      assessment7text: 'faltatexto',
      assessment7download1: 'Placement and assessment methods for soft skills in WBL situations?????faltatexto',

      humanresources1title: 'HRM Protocol???faltatexto',
      humanresources1text: 'faltatexto',
      humanresources1download1: 'faltatexto',
      // Agrega todas las traducciones
    }
  },
  eu: {
    message: {
      subtitle: 'Soft skill-ak prestatu eta garatu',
      paragraph1: 'Soft skillak interesatzen zaizkizu eta zure praktikan integratu nahiko zenituzke?',
      paragraph2: 'Soft skill-ak bizitza profesionalean funtsezkoak dira eta trebetasun eta ezagutza espezializatuak (hard skills) osatzen dituzten nortasunaren ezaugarrietatik hurbil dauden harreman eta giza trebetasunak dira. Guztiok eta gutariko bakoitzak partzialki eskuratzen ditugu, gure ibilbide profesionala edo pertsonala edozein dela ere.',
      paragraph3: 'Hala ere, gaur egun, badirudi soft skill-en prestakuntza modu naturalagoan bideratuta dagoela kualifikazio handiko pertsonengana.',
      paragraph4: 'Erasmus+ "Soft skills" proiektuaren helburua kualifikazio-maila baxuko eta/edo desgaitasuna duten pertsonei soft skill-etarako sarbidea erraztea da, haien laneratzea, gizarteratzea eta aukera-berdintasuna bultzatzeko. Jarduera profesional bat menderatzeko, lanerako trebetasun tekniko espezifikoak (hard skills) praktikan jartzeaz gain, soft skilletan ere oinarritzen da.',
      paragraph5: 'Gure ikuspegia: soft skill-ak eskuratzeko prozesu osoa kontuan hartzea. webgune honetan, doan ikus ditzakezun material osagarri ugari egin ditugu.',
      paragraph6: 'Doako material horiez gain, Zerobarrier izeneko plataforma digital bat ere badago, kuotaren arabera. Plataforma horri esker, soft skills eskuratzeko prozesua kudeatu eta jarraitu ahal izango duzu.',
      button1: 'Eragin neurketa txostena',
      subtitle2: 'Nortzuk gara?',
      partners: 'Erasmus + programak kofinantzatutako "Soft Skills" proiektu europarraren esparruan, Frantzia, Belgika, Espainia, Austria eta Esloveniako 9 bazkide europarrek garatu dituzte webgune honetan aurkituko dituzun materialak. Bazkide horiek lanbide-heziketaren esparruan lan egiten dute. Prestakuntza-zentroak, integrazio-enpresak edo enpresa egokituak direlarik, kualifikazio-maila txikia eta/edo desgaitasuna duten pertsonen prestakuntzan esperientzia dute. Egin klik logotipoetan haiei buruz gehiago jakiteko.',

      // Agrega todas las traducciones
    }
  },
  // Agrega más idiomas...
};

const i18n = createI18n({
  legacy: false, // Asegúrate de que el modo legacy esté deshabilitado
  locale: 'en',
  fallbackLocale: 'en',
  messages,
});

export default i18n;
